services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=192.168.1.116 #optional
    volumes:
      - /var/run/user/1000/docker.sock:/var/run/user/1000/docker.sock
      - /mnt/media/jellyfin/config:/config
      - /mnt/media/jellyfin/media/tvshows:/data/tvshows
      - /mnt/media/jellyfin/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
networks: {}
