#!/usr/bin/env bash

CONFIG="$HOME/.config/swaync/config.json"
STYLE="$HOME/.config/swaync/style.css"

#if [[ ! $(pidof mako) ]]; then
#	mako --config ${CONFIG}
#fi
#
if [[ ! $(pidof swaync) ]]; then
	swaync -c $CONFIG -s $STYLE
fi
